POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzA1ODY1Njg5LCJ1c2VySWQiOjF9.OqQMlvsp71cE_9E6SetICb5jfGPpZpJ5ZYqmhIUzGe0

{
    "Name": "Winter Music Concert",
    "Description": "A delightful evening of classical music performances.",
    "Location": "Grand Opera House",
    "DateTime": "2023-12-15T19:00:00Z"
}
